use_frameworks!

platform :ios, "9.0"

target 'PhotoCaptionInputView_Example' do
  pod 'PhotoCaptionInputView', :path => '../'
  pod 'MWPhotoBrowser' , :git => 'https://github.com/nixplay/MWPhotoBrowser.git', :branch => 'develop'

  target 'PhotoCaptionInputView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'

  end
end
