use_frameworks!

platform :ios, "9.0"

target 'PhotoCaptionInputView_Example' do
  pod 'PhotoCaptionInputView', :path => '../'
  pod 'MWPhotoBrowser' , :git => 'https://github.com/nixplay/MWPhotoBrowser.git', :branch => 'video_upload'
  pod 'GMImagePicker', :git => 'https://github.com/nixplay/GMImagePicker.git', :tag => 'develop'
  pod 'SDWebImage' , '4.2.2'
  pod 'ICGVideoTrimmer' , :git => 'https://github.com/nixplay/ICGVideoTrimmer.git', :branch => 'develop'
  pod 'SDAVAssetExportSession' , :git=> 'https://github.com/rs/SDAVAssetExportSession', :branch => 'master'
  pod 'IQKeyboardManager'
  target 'PhotoCaptionInputView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'

  end
end
